#!/bin/bash

IP="192.168.56.110"

if [[ $EUID -ne 0 ]]; then echo "root required" 1>&2; exit 1; fi

kubeadm init \
--apiserver-advertise-address=$IP \
--pod-network-cidr=10.244.0.0/16 \
--ignore-preflight-errors=NumCPU

# NOTE: Без --pod-network-cidr=10.244.0.0/16 не взлетит flannel

KUBECONFIG=/etc/kubernetes/admin.conf kubectl taint nodes --all node-role.kubernetes.io/master-

cat << EOF > /etc/default/kubelet
KUBELET_EXTRA_ARGS="--node-ip=$IP"
EOF

systemctl restart kubelet