#!/bin/bash

if [[ $EUID -ne 0 ]]; then echo "root required" 1>&2; exit 1; fi

apt-get update

apt-get install -qy docker.io gnupg2 apt-transport-https curl

curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" | tee /etc/apt/sources.list.d/kubernetes.list

apt-get update

apt-get install -qy kubelet kubeadm kubernetes-cni
apt-mark hold kubelet kubeadm kubectl

swapoff -a
sed -i 's/\(.*swap.*\)/#\1/g' /etc/fstab

cat << EOF > /etc/docker/daemon.json
{
  "exec-opts": ["native.cgroupdriver=systemd"]
}
EOF

systemctl restart docker

systemctl enable docker
