#!/bin/bash

if [[ $EUID -ne 0 ]]; then echo "root required" 1>&2; exit 1; fi

apt-get update

apt-get install -qy containerd gnupg2 apt-transport-https curl

curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" | tee /etc/apt/sources.list.d/kubernetes.list

apt-get update

apt-get install -qy kubelet kubeadm kubernetes-cni
apt-mark hold kubelet kubeadm kubectl

swapoff -a
sed -i 's/\(.*swap.*\)/#\1/g' /etc/fstab

modprobe br_netfilter
echo "br_netfilter" | tee /etc/modules-load.d/br_netfilter.conf

echo "net.ipv4.ip_forward = 1" | tee /etc/sysctl.d/9999-k8s.conf
echo "net.bridge.bridge-nf-call-iptables = 1" | tee -a tee /etc/sysctl.d/9999-k8s.conf
sysctl --system
